version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: mp_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: mp_kafka_ui
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092


  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: mp_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"     # доступ с хоста (Windows)
      - "29092:29092"   # не обязательно публиковать, но удобно для диагностики
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  postgres:
    image: postgres:16-alpine
    container_name: mp_postgres
    environment:
      POSTGRES_DB: media_platform
      POSTGRES_USER: mp_user
      POSTGRES_PASSWORD: mp_pass
    ports:
      - "5432:5432"
    volumes:
      - mp_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mp_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - mp_redis_data:/data

volumes:
  mp_postgres_data:
  mp_redis_data:
